# I haven't yet been able to test the output of job summary. But for now it can be done manually.

name: Pull Request

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create summary
        uses: ./
        with:
          summary: | # markdown
            # H1

            paragraph

            - item 1
            - item 2
            - item 3

            | Heading 1 | Heading 2 |
            | --- | --- |
            | col1 | col2 |
            | col1 | col2 |
