name: Release

on:
  push:
    branches: [main]

jobs:
  github:
    name: GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/git
